name: quranity
description: "Islamic Prayer Times App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.7.2

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # SVG Support
  flutter_svg: ^2.2.3

  # Device Preview
  device_preview: ^1.1.0

  # PIN Code Input
  pin_code_fields: ^8.0.1


  # Location
  geolocator:
  geocoding:

  # HTTP
  http: ^1.1.0

  # Date/Time
  intl: ^0.20.2

  share_plus: ^10.1.3
  url_launcher: ^6.2.1  # For opening app store


  # Icons
  cupertino_icons: ^1.0.8

  # Page Indicator
  smooth_page_indicator: ^1.2.0+3
  google_fonts: ^6.1.0

  image_picker: ^1.0.4



#videos play
  video_player: ^2.8.7
  cached_network_image: ^3.3.1



  ## lottery animation
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    #its for icon
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/quranitypng.png"
  remove_alpha_ios: true

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/background/
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/animations/


  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700